### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by Aamir3d** [vladmandic/sd-extension-steps-animation#11]
I get this error

Error loading script: steps_animation.py
Traceback (most recent call last):
  File "D:\Automatic1111\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Automatic1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Automatic1111\extensions\sd-extension-steps-animation\scripts\steps_animation.py", line 12, in <module>
    from modules.sd_samplers_kdiffusion import KDiffusionSampler
ModuleNotFoundError: No module named 'modules.sd_samplers_kdiffusion'

**Comment by vladmandic** [comment]
You need updated WebUI as some Imports changed.
I wish I could maintain compatility with both older and latest versions...

**Comment by Aamir3d** [comment]
> You need updated WebUI as some Imports changed. I wish I could maintain compatility with both older and latest versions...

Thank you, I'll recheck and see if it works after a git pull.
Thanks for the extension

**Comment by vladmandic** [comment]
closing issue for now, will reopen if issue persists.
