### ISSUE TITLE
How to fix this ?

### ISSUE THREAD

**Issue by clackdao** [vladmandic/sd-extension-steps-animation#9]
```
 20%|████████████████▌                                                                  | 2/10 [00:01<00:05,  1.56it/s]
Error completing request                                                  | 104/6000000 [38:00<108482:57:48, 65.09s/it]
Arguments: ('Photo cat', '', 'None', 'None', 10, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 0, True, 'x264', 'none', 10, 2, False, True, True, True, 'intermediate', 'animation', True, -1.0, False, False, False, False, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "H:\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "H:\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "H:\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = process_images(p)
  File "H:\stable-diffusion-webui\modules\processing.py", line 464, in process_images
    res = process_images_inner(p)
  File "H:\stable-diffusion-webui\modules\processing.py", line 567, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "H:\stable-diffusion-webui\modules\processing.py", line 699, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "H:\stable-diffusion-webui\modules\sd_samplers.py", line 507, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "H:\stable-diffusion-webui\modules\sd_samplers.py", line 422, in launch_sampling
    return func()
  File "H:\stable-diffusion-webui\modules\sd_samplers.py", line 507, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "H:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 148, in sample_euler_ancestral
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
  File "H:\stable-diffusion-webui\extensions\sd-extension-steps-animation\scripts\steps_animation.py", line 84, in callback_state
    image = sample_to_image(samples = d["denoised"], index = 0, approximation = None)
TypeError: sample_to_image() got an unexpected keyword argument 'approximation'
```

**Comment by vladmandic** [comment]
you've disabled previews completely and extension relies on that.
i'll add error handling, but you still need to enable it:

`settings` -> `live previews` -> `image creation progress preview mode` -> `full`
